name: Build Frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Remove old "dist" folder 
        working-directory: ./frontend
        run: |
          if (Test-Path -Path ./dist) { rm -r dist }
          

      - name: Install Deno ğŸ¦•
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build Frontend ğŸ“„
        working-directory: ./frontend
        run: |
          deno run --allow-run --allow-read https://deno.land/x/snel/install.ts
          trex run build
          if (Test-Path -Path ./trex_storage) { rm -r trex_storage }
      
      - name: Copy Images ğŸ–¼ï¸
        working-directory: ./frontend
        run: |
          copy -r .\public\images\ .\dist\

      - name: Commit & Push changes âœ”ï¸
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'